# actuator相关配置, 用于springboot admin服务监控
management:
  endpoints:
    web:
      exposure:
        # 暴露所有监控节点
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  # 使用独立的 121 端口而不是提供业务的端口作为服务监测的端口, 这样可以方便的进行防火墙配置, 避免外网访问
  server:
    port: 121
spring:
  cloud:
    consul:
#      host: 10.31.110.124
      host: 121.4.39.153
      port: 8500
      discovery:
        enabled: false
      enabled: false
#spring:
#  cloud:
#    consul:
#      host: 121.4.39.153
#      port: 8500
#      discovery:
#        enabled: true
#        register: true
#        deregister: true
#        prefer-ip-address: true
#        health-check-path: /check
#        heartbeat:
#          enabled: true

logging:
  file:
    path: /etc/log
    name: mqtt.log
  level:
    root: info

